### ISSUE TITLE
About CHROM method

### ISSUE THREAD

**Issue by wang-tf** [ubicomplab/rPPG-Toolbox#139]
Thanks very much about your job !

I have a question about this line:
https://github.com/ubicomplab/rPPG-Toolbox/blob/be4a0ac1d918089876bb673eb7667e1f7fde8c27/unsupervised_methods/methods/CHROME_DEHAAN.py#L36

About the nomalization method in CHROM, it only used $\frac{C_i}{\mu (C_i)}$ in my opinion, without  using `- 1`.

`- 1` was used in `XoverY`, not in `XsminYs`. Is there any problem in my point ?

**Comment by yahskapar** [comment]
Hi @wang-tf,

Based on my reading of the paper<sup>1</sup> and after taking a look at this code, I think this implementation is still correct. Note that the line of code you highlighted is associated with XoverY rather than X<sub>s</sub>minαY<sub>s</sub>. The code associated with X<sub>s</sub>minαY<sub>s</sub> in this implementation is on lines 42 and 43:

https://github.com/ubicomplab/rPPG-Toolbox/blob/be4a0ac1d918089876bb673eb7667e1f7fde8c27/unsupervised_methods/methods/CHROME_DEHAAN.py#L42-L43

Line 36 you pointed out corresponds to equation (5) below, from the paper<sup>1</sup>:

$$S = \frac{X_n}{Y_n}-1$$

Again, which composes the XoverY algorithm. X<sub>s</sub>minαY<sub>s</sub> is described by equations (14):

$$S = X_f - \alpha Y_f$$

Where $\alpha = \frac{\sigma{(X_f)}}{\sigma{(Y_f)}}$ and therefore corresponds to the aforementioned lines 42 and 43. You are correct that when $\frac{C_i}{\mu (C_i)}$ is first introduced as equation 2 that there is no subtraction of 1, but then that subtraction of 1 shows up in equation (5). Although I don't think it's explicitly stated why in the paper, I believe this is so that the distribution of the normalized result can be centered around 0, which in turn may make it easier to work.

I think your confusion may have been with viewing line 36 to have to do with X<sub>s</sub>minαY<sub>s</sub>, which i don't think is the case. Let me know if you still find something off in the CHROM implementation, I'm happy to try and dive into figuring out what's wrong. I did notice some unnecessary code in the CHROM implementation that I will make a PR to remove, but that will be totally unrelated to the concern you expressed in this issue.

<sup>1</sup> De Haan, G., & Jeanne, V. (2013). Robust pulse rate from chrominance-based rPPG. IEEE Transactions on Biomedical Engineering, 60(10), 2878-2886.

**Comment by wang-tf** [comment]
Thanks @yahskapar, your answer is very helpfull!

There is a confusion still in my mind. In the paper<sup>1</sup>, four methods were introduced:
1. $RoverG$ was described by equation 3:
2. $XoverY$ was described by equation 5;
3. $Fixed$ was described by equation 8;
4. $X_s min \alpha Y_s$ described by equation 14;

There are different ways to get the blood volume pulse signal. And the normalizaiton method described by equation 2 is the preprocessing method.

In my point, the code will like:
```python
    for i in range(NWin):
        # normalization (eq 2)
        RGBBase = np.mean(RGB[WinS:WinE, :], axis=0)
        RGBNorm = np.zeros((WinE-WinS, 3))
        for temp in range(WinS, WinE):
            RGBNorm[temp-WinS] = np.true_divide(RGB[temp], RGBBase)

        # X_s min \alpha Y_s (eq14)
        Xs = np.squeeze(3*RGBNorm[:, 0]-2*RGBNorm[:, 1])
        Ys = np.squeeze(1.5*RGBNorm[:, 0]+RGBNorm[:, 1]-1.5*RGBNorm[:, 2])
        Xf = signal.filtfilt(B, A, Xs, axis=0)
        Yf = signal.filtfilt(B, A, Ys)
        Alpha = np.std(Xf) / np.std(Yf)
        SWin = Xf-Alpha*Yf

        SWin = np.multiply(SWin, signal.hanning(WinL))
```


1 De Haan, G., & Jeanne, V. (2013). Robust pulse rate from chrominance-based rPPG. IEEE Transactions on Biomedical Engineering, 60(10), 2878-2886.

**Comment by yahskapar** [comment]
Hi @wang-tf,

I may still be confused as to what your question is exactly, are you trying to figure out what parts of the code correspond to which equations, or do you feel there is some mistake that is influencing some kind of result that you are getting? Please clarify further. Also, I realized I may have confused you with an incorrect statement in my previous reply regarding equation 5 from the paper being present in the implementation in the code in this repo, so allow me to correct myself.

Note that equations 3, 5, and 8, corresponding to _RoverG_, _XoverY_, and  _Fixed_  don't appear at all in the code since they are concluded to be ineffective for various reasons in the original paper<sup>1</sup>. X<sub>s</sub>minαY<sub>s</sub> is concluded to have the cleanest spectrum, among other benefits noted throughout the paper, so that is the final proposed algorithm and what is included in this repo from what I understand.

Your main confusion has to do with the normalization below and equation (2) from the paper I believe:

https://github.com/ubicomplab/rPPG-Toolbox/blob/be4a0ac1d918089876bb673eb7667e1f7fde8c27/unsupervised_methods/methods/CHROME_DEHAAN.py#L35-L36

Equation 2 is given as:

$\frac{C_i}{\mu (C_i)}$

Equation 3 is given as:

$S_{i} = \frac{G_{ni}}{R_{ni}} - 1 = \frac{G_{i}}{R_{i}} \cdot \frac{\mu (R_i)}{\mu (G_i)}$

$G_{ni}$ and $R_{ni}$ are the normalized green and red color channels respectively from the above equations, and as you can see they correspond to equation 2 but have the additional minus 1 to center the data around 0 after dividing the color value by the mean color value for that window. This is a fairly common step to center the data after normalization. You can try for yourself by including or excluding the - 1 term, you should note it doesn't really make a significant difference with respect to the final result but does stay true to the normalization technique used by the original paper<sup>1</sup>.

Let me know if that still doesn't clear your doubts, I'm curious if there is something else you see off that I'm not catching quite well.

<sup>1</sup> De Haan, G., & Jeanne, V. (2013). Robust pulse rate from chrominance-based rPPG. IEEE Transactions on Biomedical Engineering, 60(10), 2878-2886.

**Comment by wang-tf** [comment]
Thanks @yahskapar , I fully agree with your point of view.

1. $X_s min \alpha Y_s$ is the final proposed algorithm;
2. `- 1` term may not influence the result.

In my opinion, the reason using equation (2) normalizon is to remove the influence introduced by brighness level of the light source. So dividing the mean over a temporal interval is helpful. About the distribution around 0 by using `-1`, I don't know its helpful currently.

**Comment by yahskapar** [comment]
Great, and yes, I don't think the `- 1` term is helpful as well. It will be removed in #145. 

I'll go ahead and close this issue now that it seems there are no other questions, but if you notice anything with your continued use of the toolbox, please feel free to create another issue!
