### ISSUE TITLE
About gt_hr when using FFT method

### ISSUE THREAD

**Issue by GaoXu007** [ubicomplab/rPPG-Toolbox#152]
hi~

I've observed that the `gt_hr` values obtained via the following two methods exhibit inconsistencies(on **UBFC** dataset).

1. default method: [read_wave()](https://github.com/ubicomplab/rPPG-Toolbox/blob/b63bcc90576c26afbbf50ff859f5df3739bc248b/dataset/data_loader/UBFCLoader.py#LL74C29-L74C29)--->[calculate_metric_per_video](https://github.com/ubicomplab/rPPG-Toolbox/blob/b63bcc90576c26afbbf50ff859f5df3739bc248b/unsupervised_methods/unsupervised_predictor.py#L54)--->`gt_hr_fft_all`
2.  by reading the **FFT** column in the `wip/label/comparison_UBFC.csv` file.

However, for certain subjects, the results derived from these two methods are inconsistent.

|    |      default      |  comparison_UBFC.csv |
|----------|:-------------:|------:|
| subject 8 |  112.5 | 101.07 |
| subject 10 |    119.53125   |   108.984375 |
| subject 14 | 77.34375 |    70.3125 |
| subject 16 | 94.48242188 |    90.96679688 |
| subject 24 | 95.80078125 |    87.01171875 |

What factors contribute to this difference?  
How are the manually corrected values in `comparison_UBFC.csv` derived?
When executing the program, which reference value should be selected?

thanks!

**Comment by yahskapar** [comment]
Hi @GaoXu007,

One key thing that can affect certain values are the cut-off frequency values for filters utilized. You can find the values we use in the `calculate_metric_per_video()` function [here](https://github.com/yahskapar/rPPG-Toolbox/blob/main/evaluation/post_process.py#L99). Cut-off frequencies of 0.75 and 2.5 Hz are used. I don't think that's what's causing the discrepancy you see, however, since none of those values seem particularly close to the cut-offs which are equivalent to 45 and 150 beats/min.

A possibility is that the values in the `.csv` file you pointed out were calculated using the [peak detection method](https://github.com/yahskapar/rPPG-Toolbox/blob/main/evaluation/post_process.py#L46) rather than the [FFT method](https://github.com/yahskapar/rPPG-Toolbox/blob/main/evaluation/post_process.py#L35) which you pointed out as the default method. I'm not really sure of the history behind that `.csv` file, maybe @xliucs could help us out there.

**Comment by yahskapar** [comment]
Hi @GaoXu007,

I'll close this for the time being since there appears to be no further discussion at the moment, please feel free to re-open if you can or create a new issue if your concerns persist. I personally think utilizing the default method you alluded to in your original post is the way to go, especially since all of the [benchmarks](https://github.com/ubicomplab/rPPG-Toolbox#bar_chart-benchmarks) provided with this toolbox have utilized that method.
