### ISSUE TITLE
Question about label_type in preprocess

### ISSUE THREAD

**Issue by Dylan-H-Wang** [ubicomplab/rPPG-Toolbox#202]
Hi,

I am trying to understand the logic behind label_type preprocessing:
1. For efficientPhys ([config file](https://github.com/ubicomplab/rPPG-Toolbox/blob/main/configs/train_configs/UBFC-rPPG_UBFC-rPPG_PURE_EFFICIENTPHYS.yaml)), the data type is set to `Standardized` but the label type is set to `DiffNormalized`. Is that possibly a bug, since I saw the original paper was using `DiffNormalized` inputs?
2. I saw that for all datasets, the label type is set to `DiffNormalized` instead of `Raw` or `Standardized`. Does is mean asking the model to predict the difference of rPPG is more helpful than directly predicting actual rPPG signals?
3. If outputs of the model is set to rPPG difference, how can we obtain the actual rPPG signals during the inference?

Thank you!

**Comment by yahskapar** [comment]
Hi @Dylan-H-Wang,

1. Not a bug, this has more to do with the EfficientPhys-C implementation utilized having its own normalization module that ultimately calculates difference frames. Check out the two lines [here](https://github.com/ubicomplab/rPPG-Toolbox/blob/main/neural_methods/model/EfficientPhys.py#L97-L98) which I believe are relevant.

2. Not sure if there is some confusion of terminology here, but the reason we use `DiffNormalized` as you pointed out is because the data type is `DiffNormalized`, whether it's set to that explicitly for pre-processing as an input or it eventually becomes that through a module such as the one mentioned in my first answer above. The 1st derivative of the PPG signal is being predicted.

3. The output of the models are effectively the 1st derivative of the PPG signal. Check out [this](1st derivative of PPG signal) section in the README for visualizing the outputs. This should also give you an idea on how to use the `.pkl` files mentioned for your own code. You can also consider saving the predicted and ground truth signals just before they're used for HR calculations [here](https://github.com/ubicomplab/rPPG-Toolbox/blob/527a74fb62c2bb175585b1337759e859118aa190/evaluation/post_process.py#L111-L112).

Hope this helps.

**Comment by Dylan-H-Wang** [comment]
Thank you for the answer. Problem is solved and close.
