### ISSUE TITLE
unsupervised method test-data predictions and labels

### ISSUE THREAD

**Issue by kimyongdo1** [ubicomplab/rPPG-Toolbox#205]
hi 
First of all, thank you very much for your contribution to this field. This toolbox is excellent.

Currently, the neural network method can output RPPG data and display images.
STEP 1: Specify the TEST.OUTPUT_SAVE_DIR field in the .yaml config file of a neural method experiment.
STEP 2: Run the neural method experiment. A .pickle file containing the test-data predictions and labels will be created in TEST.OUTPUT_SAVE_DIR.

I would like to know how to output data and display images using unsupervised methods?

THANK YOU ~

**Comment by yahskapar** [comment]
Currently, this functionality is not available with unsupervised methods. @girishvn implemented this functionality with neural methods and he or someone else may be able to extend it to unsupervised methods sometime in the near future.

**Comment by kimyongdo1** [comment]
If I generate RPPG data in an unsupervised manner, which variable should I save to obtain this data?

**Comment by girishvn** [comment]
Hi @kimyongdo1 you can save the `BVP` variable in the `unsupervised_predictor.py` file to save method outputs (this is the predicted BVP signal for the entirety of a sample video).
I will implement the functionality to save this data in the near future.

**Comment by yahskapar** [comment]
You could try saving `BVP` after this empty line [here](https://github.com/ubicomplab/rPPG-Toolbox/blob/main/unsupervised_methods/unsupervised_predictor.py#L48) in `unsupervised_predictor.py`. One idea is to create a new dict just outside the for loop further above in that same file, and then append each `BVP` to that dict. At that point all you'd have to do is run your own post-processing code, or borrow post-processing code related to metric calculation [here](https://github.com/ubicomplab/rPPG-Toolbox/blob/main/evaluation/post_process.py#L99).

You could also modify that `calculate_metric_per_video()` function to return the post-processed BVP/PPG signals and append those instead of what I mentioned above.

**Comment by kimyongdo1** [comment]
Got it， thank you all^^

**Comment by yahskapar** [comment]
I'm going to go ahead and close this issue since there doesn't appear to be any further discussion and, as @girishvn mentioned, functionality to save the data for unsupervised methods will be implemented in the near future. @kimyongdo1, feel free to re-open if needed, or create a new issue if you run into any other problem.
