### ISSUE TITLE
How to get HRV or BPM on your own video?

### ISSUE THREAD

**Issue by syami** [ubicomplab/rPPG-Toolbox#208]
Hi,
I could not find any documentation on how to obtain HRV or BPM using an existing trained model on your own video.
Can you point me to the correct documentation?

**Comment by yahskapar** [comment]
Hi @syami,

Since this toolbox is targeted toward effectively designing and benchmarking algorithms for remote photoplethysmography (rPPG), we don't readily have any kind of feature that gives you those results on a self-recorded video or other videos not explicitly captured for rPPG. However, if you treat your custom video, or videos plural, as a dataset, you should be able to obtain results on your video using a mixture of the instructions [here](https://github.com/ubicomplab/rPPG-Toolbox#open_file_folder-adding-a-new-dataset) and either utilizing unsupervised methods or treating your custom method as an unsupervised method based on the instructions [here](https://github.com/ubicomplab/rPPG-Toolbox#chart_with_upwards_trend-adding-a-new-unsupervised-algorithms). Excuse the typo on the step numbering, that will be fixed in a future revision of the README.

Alternatively, you could follow the same aforementioned custom dataset instructions and instead use pseudo-PPG labels as described briefly [here](https://github.com/ubicomplab/rPPG-Toolbox#green_book-weakly-supervised-training). A simple example of how to enable that can be seen in some of the BP4D dataset training config files, for example [here](https://github.com/ubicomplab/rPPG-Toolbox/blob/main/configs/train_configs/BP4D_BP4D_PURE_DEEPPHYS_BASIC.yaml#L19).

Give those options a try and feel free to reach out here again with specific questions. All the best!

**Comment by yahskapar** [comment]
I'll go ahead and close this given the lack of discussion, but feel free to re-open and comment again if you happen to have any questions after going through the information in my previous reply, @syami.
