### ISSUE TITLE
Question about creating database based on hands

### ISSUE THREAD

**Issue by Kunyro** [ubicomplab/rPPG-Toolbox#218]
Hi,

I am interested in using neural network rPPG technology to detect peoples heart rate based on the palm of their hands. How would I go about doing that/is it even doable? Will something like DeepPhys work if trained on hands instead of faces? I am a bit of a noob but I am very interested in this technology and how to use it.

Thank you for the help

**Comment by yahskapar** [comment]
Hi @Kunyro,

My understanding is existing unsupervised, signal processing-based methods like POS and CHROM should work, as well as maybe neural methods (such as DeepPhys) given you can utilize psueod-labels, an existing dataset, or make your own curated dataset. I should note that you would have to make certain changes to this toolbox pipeline in order to achieve that, especially since this toolbox is focused on detecting and cropping to faces in particular for the rPPG task. I personally don't think this is too difficult, and if you have specific questions on how to re-purpose this toolbox's pipeline for other potential parts of the body for rPPG, we would be happy to help with any problems you might encounter as you dig into things.

I find multi-site physiological monitoring to be interesting and there is definitely a possibility we could add support for that kind of dataset later on in the future. I think you will find [this recent paper](https://arxiv.org/abs/2303.09638) to be an especially interesting read. The authors of that paper also released a dataset, the Multi-Site Physiological Monitoring (MSPM) dataset, which you should be able to get your hands on after filling out a form [here](https://cvrl.nd.edu/projects/data/#multi-site-physiological-monitoring-mspm-dataset).

All the best!

**Comment by Kunyro** [comment]
Alright,
Very useful, thank you so much for the response.
I will contact you if I have any more questions in the future

Thanks a lot
