### ISSUE TITLE
Using Pretrained Weights for prediction

### ISSUE THREAD

**Issue by amishparekh** [ubicomplab/rPPG-Toolbox#230]
Hi,
How do I use the pretrained weights for prediction? I tried to load them but when trying to use it I am getting errors for input shape.. I am certain, I am doing something wrong..could you help me out?

**Comment by yahskapar** [comment]
Hi @amishparekh,

Can you please share more details regarding what exactly you are doing (e.g., running an inference config?) and what the exact errors are? Feel free to include copied/pasted terminal outputs or screenshots.

Generally speaking, you should be able to utilize the pre-trained models quite easily for inference using any of the example inference configs as mentioned [here](https://github.com/ubicomplab/rPPG-Toolbox#computer-example-of-using-pre-trained-models) in the README.

**Comment by yahskapar** [comment]
@amishparekh,

Check out my reply [here](https://github.com/ubicomplab/rPPG-Toolbox/issues/208#issuecomment-1718892753) that should be relevant. This toolbox's code is completely open-source, so you should be able to to match the preprocessing and postprocessing steps. 

If you give this a try, or have given this a try already, after considering the existing code, feel free to ask specific questions with your code included - otherwise, it's impossible to help you without more context on your code and where there might be a bug.

**Comment by amishparekh** [comment]
@yahskapar ,
Thanks for the prompt reply.. I will try out again and let you know if I have some concerns.
