### ISSUE TITLE
palmvein

### ISSUE THREAD

**Issue by peizhengfu** [ubicomplab/rPPG-Toolbox#234]
Hello, I want to use this toolbox to extract rppg from palm veins. Is it feasible?

**Comment by yahskapar** [comment]
Hi @peizhengfu,

It should be feasible to explore. I'd recommend seeing if you can extract a signal using an unsupervised method like POS first, then moving on to neural methods and either trying a pre-trained model to see if it can get any reasonable signal (unlikely) or trying to train, or fine-tune, a model on data that has palm veins captured. 

You should definitely take a look at this [full body cardiovascular sensing paper](https://openaccess.thecvf.com/content/CVPR2023W/CVPM/papers/Niu_Full-Body_Cardiovascular_Sensing_With_Remote_Photoplethysmography_CVPRW_2023_paper.pdf) which has a [multi-site physiological monitoring (MSPM) dataset](https://cvrl.nd.edu/projects/data/#multi-site-physiological-monitoring-mspm-dataset) associated with it. I haven't read this other paper [here](https://opg.optica.org/optcon/fulltext.cfm?uri=optcon-2-12-2540&id=544083) that cited the aforementioned paper yet, but it also looks interesting and appears to include measurement of the palm in addition to a novel measurement of the foot sole.

Since there appears to be a fair amount of questions regarding non-face sites for rPPG, we will try to add dataset support for MSPM or other similar datasets in the near future.

**Comment by peizhengfu** [comment]
Thank you very much for your feedback and suggestions
