### ISSUE TITLE
what changes to make to train a deep learning model on the cloud using the rppg-toolbox

### ISSUE THREAD

**Issue by ahmedkhalid7** [ubicomplab/rPPG-Toolbox#245]
I am beginner to deep learning and training deep learning models on cloud services. I know how to add a new model to the provided toolbox based on what is written in the readme file, but I don't know if there are any changes that I need to make to be able to train the model on a cloud service like Microsoft Azure. You did not mention about how we could train that model, so if you have any resources or notes that I need to consider to be able to train a model using the provided toolbox, that would help me for sure!

**Comment by yahskapar** [comment]
Hi @ahmedkhalid7,

We haven't really had any folks request these kinds of directions, partly because it should be straightforward to use whatever CLI support a cloud service has in order to clone and run this toolbox with provisioned resources (e.g., CPUs, GPUs). In the case of Microsoft Azure, take a look at the instructions [here](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-train-model?view=azureml-api-2&tabs=python). You should be able to use either the Azure Python SDK or the Azure CLI to work with this toolbox at that point.

For the time being I'll close this issue as that should answer your question, but give the linked instructions alongside this toolbox's README a try and let us know if you run into any issues that are specific to this toolbox.
