### ISSUE TITLE
ERROR: No Face Detected

### ISSUE THREAD

**Issue by 408550969** [ubicomplab/rPPG-Toolbox#268]
Hi, when I run the test set and report Error: No Face Detected twice, will these two folders that did not detect faces be taken for testing, and will this affect the MAE?

**Comment by yahskapar** [comment]
Yes, they will still be included in the test split. Due to the face detection failure, the only difference is that the whole frame of the original video will be used and resized to whatever resolution specified (e.g., 72x72) rather than just the face region.

Out of curiosity, what dataset are you encountering this error with? In your config, are you using the default Haar Cascade (`HC`) approach for face detection? If so, maybe try RetinaFace (`RF`) instead. RetinaFace should generally allow for better face detection results, but part of the reason it isn't used by default is the benchmark results in [the NeurIPS 2023 paper](https://proceedings.neurips.cc/paper_files/paper/2023/hash/d7d0d548a6317407e02230f15ce75817-Abstract-Datasets_and_Benchmarks.html) all happened to use Haar Cascade.

**Comment by 408550969** [comment]
Thank you, I roughly understand why the MAE has reached such a high of 7. I used some infrared videos I collected myself, and since the camera is tilted, the face I obtained has a certain angle. I used default face detection

**Comment by 408550969** [comment]
When I changed HC to RF, the following error was reported:
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rPPG-Toolbox-main/dataset/data_loader/UBFCrPPGLoader.py", line 93, in preprocess_dataset_subprocess
    frames_clips, bvps_clips = self.preprocess(frames, bvps, config_preprocess)
  File "/home/rPPG-Toolbox-main/dataset/data_loader/BaseLoader.py", line 224, in preprocess
    frames = self.crop_face_resize(
  File "/home/rPPG-Toolbox-main/dataset/data_loader/BaseLoader.py", line 372, in crop_face_resize
    face_region_all.append(self.face_detection(frames[detection_freq * idx], backend, use_larger_box, larger_box_coef))
  File "/home/rPPG-Toolbox-main/dataset/data_loader/BaseLoader.py", line 301, in face_detection
    res = RetinaFace.detect_faces(frame)
AttributeError: type object 'RetinaFace' has no attribute 'detect_faces'
