### ISSUE TITLE
cohface dataset errors

### ISSUE THREAD

**Issue by zzw121915** [ubicomplab/rPPG-Toolbox#270]
Hello, I am getting errors when preprocessing the cohface dataset：
[mpeg4 @ 000001c693cbe6c0] slice end not reached but screenspace end (66 left 6D0F1E, score= -1168)
Have you ever encountered such a problem? Excuse me for interrupting
![03e800044aac4bc3d9e42365ffd8043](https://github.com/ubicomplab/rPPG-Toolbox/assets/76432594/fdb867c4-ac19-4f85-89b8-5b63a3344c89)

**Comment by yahskapar** [comment]
Hi @zzw121915,

How exactly did you download the videos? Are you sure the download itself hasn't been corrupted somehow (e.g., are you able to view the videos properly otherwise)? 

I can't say I'm familiar with that particular error, and unfortunately despite the existence of a COHFACE dataloader and some references to COHFACE in this repo, COHFACE still isn't yet supported by this toolbox.

**Comment by zzw121915** [comment]
I re-downloaded the dataset and checked the videos, but there were still errors. Maybe I need to try something else. Thank you for your reply. Everything went well.

**Comment by yahskapar** [comment]
I'll go ahead and close this issue now since COHFACE isn't fully supported by this toolbox (yet), but feel free to re-open if you happen to figure out what's wrong and are able to share here for everyone benefit.
