### ISSUE TITLE
iBVP_iBVPNet_DiffNormalized.pth is a damage file only size is : 1k

### ISSUE THREAD

**Issue by 202228061383** [ubicomplab/rPPG-Toolbox#283]
iBVP_iBVPNet_DiffNormalized.pth is a damage file only size is : 1k

**Comment by yahskapar** [comment]
Hi @202228061383,

Thanks for the heads up. @jnj256, can you look into this and make a PR for fixed model file? Thanks!

**Comment by yahskapar** [comment]
Hi @202228061383,

@jnj256 will update the repo with the model by this weekend, but for now feel free to use this as provided him: [link](https://liveuclac.sharepoint.com/:u:/s/PhysiologicalComputingLab/EdS1yjxX9PxNnV544YXyhdwB5YkdIJ3aaZJV0X1sBqvETA).

I'll close this issue now that this is resolved with the above link in the short-term and will be resolved in the repo by the weekend or so.

**Comment by Ishtiaque-khan97** [comment]
@yahskapar @jnj256 
I think the file was not updated, It is still a damaged file. Could you please update it?
Thank you.

**Comment by yahskapar** [comment]
Hi @Ishtiaque-khan97,

Are you sure you fetched the latest changes from the repo or are checking from the GitHub website rather than a local clone? I was able to download the file (~8.7MB once downloaded) and it seems fine, did you download it, try using it, and then find some other issue? Can you provide more details if so?

**Comment by yahskapar** [comment]
@Ishtiaque-khan97,

This was recently updated by @jnj256, so the models there that do work are what's intentionally being released for now I believe. If you want to request access to more pretrained models, your best bet would be to reach out to the owner of those models directly (e.g., via email at the bottom of [their webpage](https://jnj256.github.io/)).

**Comment by jnj256** [comment]
@Ishtiaque-khan97: Since in the [iBVP dataset paper](https://www.mdpi.com/2079-9292/13/7/1334), we do not present results of the models trained with iBVP dataset, it was removed from our official release here. If you have access to the iBVP dataset, it should be straightforward to train the model with it.

**Comment by Ishtiaque-khan97** [comment]
thank you both for the clarifications and also for keeping the toolbox up to date.
