### ISSUE TITLE
About Adding Moving Scene Data

### ISSUE THREAD

**Issue by 408550969** [ubicomplab/rPPG-Toolbox#290]
I added a lot of speech and slight turning scenes, and the ratio of moving and static scenes is about 3:1. The total video is 130 minutes. I found that compared to pure static scenes, the model's MAE did decrease, but the actual test results were very poor (inference every 6 seconds). The predicted heart rate fluctuated around the true heart rate, for example, if the true value is 80, then the predicted result fluctuates randomly between 100-60. My feeling is that the model overfits, and the loss ends up around 0.7.
When I removed all the motion scenes, the loss decreased to 0.3, and although the MAE increased, the actual test results were much more accurate than before. When the prediction time was increased to 30 seconds, accurate values could also be obtained for speech and slight turning scenes.
So my question is whether it is useful to add scenes such as speeches.

**Comment by yahskapar** [comment]
Hi @408550969,

Thanks for using the toolbox! It's totally up to you whether or not to add such scenes as a part of your experiments. If you're referring to adding a new dataset to the toolbox, feel free to follow the instructions [here](https://github.com/ubicomplab/rPPG-Toolbox?tab=readme-ov-file#open_file_folder-adding-a-new-dataset) and make a pull request for this repo. We would greatly appreciate your contribution if it seems reasonable to include in the toolbox!

For the time being I'll close this issue since it doesn't relate to a pressing question or concern with the toolbox's functionality itself. Feel free to make a new issue if you run into any troubles with the toolbox.
