### ISSUE TITLE
Is it normal for a bunch of red and green dots to appear in the pre-processing when I am stationary?

### ISSUE THREAD

**Issue by jungyin** [ubicomplab/rPPG-Toolbox#314]
I am trying to generate a heart rate using rppg toolbox, but the generated heart rate has been unstable. When displaying the preprocessed image, I found that when it is completely stationary, there are some small red and green dots inside. Is this normal?

and this is a screenshot that I prohibit from moving
![image](https://github.com/user-attachments/assets/028e7d13-8dfe-4fe0-9633-2ed05d38518c)
This is the image generated when I tried to move slightly
When I move slightly, there are very few red and green dots on my face, and the white part seems to be very similar to the white part when the RPPG signal is generated in the sample dataset

**Comment by jungyin** [comment]
I seem to have missed the second picture, let's add it now
![image](https://github.com/user-attachments/assets/452e238f-b7fe-4874-9a17-acd72c412fe0)

**Comment by girishvn** [comment]
Hi @jungyin,

rPPG is notoriously sensitve to motion artifact. There is a lot of work, including Motion Matters (implemented in this toolbox) that explores how to make these systems more robust. 

The green / red artifacts you see are normal. They are artifacts from subtle motion. 
The best way to get stable HR is too stay fairly still or to add motion artifacts as part of training to my the models for resistant to this.

**Comment by jungyin** [comment]
> Hi @jungyin,
> 
> rPPG is notoriously sensitve to motion artifact. There is a lot of work, including Motion Matters (implemented in this toolbox) that explores how to make these systems more robust.
> 
> The green / red artifacts you see are normal. They are artifacts from subtle motion. The best way to get stable HR is too stay fairly still or to add motion artifacts as part of training to my the models for resistant to this.

May I ask how to use RPPG Toolbox for heart rate calculation? I followed the training module trained on the model and preprocessed the results before injecting them into the model. After post-processing, the heart rate changes significantly, which is what worries me

**Comment by jungyin** [comment]
and,this is my code 
![image](https://github.com/user-attachments/assets/739d4e54-b42b-41b9-b1fd-a15db8cc73fc)

**Comment by yahskapar** [comment]
Hi @jungyin,

I'll reiterate what I said in some of your other issues: it seems like you're heavily modifying (some) aspects of the toolbox, not sharing enough context as to why, and expecting us to be able to help you given the aforementioned.

I recommend asking more specific questions and telling us a bit about what exactly you're trying to do, perhaps in a brand new issue since at least part of your somewhat vague, original concern was already answered in this issue. Furthermore, this is a fully open-source toolbox - you can ask questions about how to integrate some part or another into another code base, but you can't expect the toolbox maintainers, or anyone really, to try and debug your custom code for you.
