### ISSUE TITLE
Discussion about the performance on predicting high heart rate (>100bpm)

### ISSUE THREAD

**Issue by hansonchen1996** [ubicomplab/rPPG-Toolbox#324]
First of all, thanks for your amazing work.

However, in the official example of Bland-Altman plots (i.e., TSCAN trained with the UBFC-rPPG dataset and testing on the PURE dataset), there are several outliers with >100 bpm GTs and < 80 bpm predictions. I wonder if you guys have any ideas on this phenomenon. Thanks.

**Comment by yahskapar** [comment]
Hi @hansonchen1996,

There's a number of possibilities regarding the phenomenon you pointed, but generally speaking I think it has something to do with the training data (UBFC-rPPG in this case) not being able to handle the domain shift to PURE with respect to things like motion artifacts. Motion artifacts, including the somewhat subtle ones in the PURE dataset, definitely can be challenging to deal with due to the additional noise.

For what it's worth, one of my prior works (which is supported by this toolbox) can be found [here](https://github.com/yahskapar/MA-rPPG-Video-Toolbox) and actually handles some of those outliers you mentioned. Check out this figure from [my paper](https://arxiv.org/abs/2303.12059), for example, that shows augmenting the UBFC-rPPG data with motion improves the results and only allows for one significant outlier in the case of PURE:

![Screenshot from 2024-10-17 01-03-22](https://github.com/user-attachments/assets/cd05ac7e-0865-4fcf-b67c-2e476b16dffd)

I'd be curious what video corresponds to that particular outlier is - unfortunately, I don't remember off the top of my head nor can I quickly check that at the moment. It's possible that, aside from motion artifacts, other differences such as lighting and background content that confuse TS-CAN somehow could be problematic, and perhaps that is more apparent with other test datasets such as MMPD.

**Comment by hansonchen1996** [comment]
Thank you. That helps a lot!
