### ISSUE TITLE
Use of 'PURE-PURE-iBVP-iBVPNet'

### ISSUE THREAD

**Issue by creaycoder** [ubicomplab/rPPG-Toolbox#330]
I'm using the iBVPNet model. Specifically, I use 'PURE-PURE-iBVP-iBVPNet.yaml' to use the iBVPNet model. Due to the collective size of the data, I only used a portion of the two data sets described. I ran the model training and validation all right, but I ended up with the following error, and the folder 'saved_test_outputs' was not found, and the generated folder 'saved_test_outputs' was empty. I would like to ask you, what is the reason? Have you encountered it?
![6a61a5e3964e17d5a0b13cf2bd44124](https://github.com/user-attachments/assets/37b26f42-8836-46f0-bda2-64c490e0dc90)
![8af4a0b19b8439c8239869936e72504](https://github.com/user-attachments/assets/494ec41f-1863-4b52-bde1-2aecbf7b99df)

**Comment by yahskapar** [comment]
Hi @creaycoder,

I think this is because of your sample size (in this case, number of videos in the test dataset) is too small, and therefore the  covariance matrix for the Pearson correlation calculation isn't well-defined. Can you try increasing the test dataset to perhaps add a few more videos (perhaps two more on top of the existing two)? 

Alternatively, in the `TEST` section of your config file, you can just remove the Pearson metric. That should avoid this error and allow you to see the additional test-time outputs.

**Comment by yahskapar** [comment]
Closing this due to the lack of follow-up discussion, but please let us know if you continue having issues @creaycoder.
