### ISSUE TITLE
what is the CUDA version to install?

### ISSUE THREAD

**Issue by mafifkasno** [ubicomplab/rPPG-Toolbox#341]
I am using RTX 4060 ti with ubuntu 20.04, nvidia-smi 550.135 and CUDA Version 12.4. but when I tried to install the requirement.txt, i am facing some issues of incompatible version for pytorch and causal-conv1d package : 

RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.6) mismatches the version that was used to compile
      PyTorch (11.8). Please make sure to use the same CUDA versions.
      
However, I cannot downgrade to PyTorch 11.8 due to NVIDIA 520 is not supporting RTX 4060ti. 

Please help.

**Comment by yahskapar** [comment]
Hi @mafifkasno,

I'm a bit confused by some of the details in your post since it doesn't quite match what the toolbox tries to install specific to the conda environment (i.e., a compiled version of CUDA 12.1). Did you manually try updating your version of CUDA based on an initial mismatch? Also, what does "NVIDIA 520 is not supporting RTX 4060ti" mean? Is 520 referring to an older driver version?

Seems like you have the latest driver for that specific GPU (NVIDIA RTX 4060 Ti) and you just need to install the right version of CUDA (in this case, maybe 11.8 though I would carefully re-read the error messages you're getting) or make sure the right version of CUDA is selected. Try following the instructions [here](https://freedium.cfd/https://towardsdatascience.com/managing-multiple-cuda-versions-on-a-single-machine-a-comprehensive-guide-97db1b22acdc#b45b) to install the right version of CUDA and make sure you have it selected properly (especially important when you have multiple versions on your machine).

**Comment by yahskapar** [comment]
Closing due to lack of further discussion, but please do let us know if your issues persist @mafifkasno.

**Comment by mafifkasno** [comment]
Apologies but I still have a question. I still facing issues of incompatibilities of libraries version especially numpy and scipy. My current installation setup (after so many attempts):

ubuntu 20.04
(RTX 4060ti) NVIDIA-SMI 550.135 Driver Version: 550.135 CUDA Version: 12.4  
torch 2.6.0a0+gita5fb07a
Python 3.9.21
numpy 1.21.6
scipy [still cannot get correct version]

due to RTX 4060ti, I have to use Driver version 550 and CUDA 12.4, however, due to python 3.8 not supporting these newer version, I have to opt to python 3.9. Then still some dependencies and libraries version mismatch during installation.

Or could you please share the list of the installation libraries version which can work with RTX 4060ti? Thank you!
