### ISSUE TITLE
some issues about Physnet

### ISSUE THREAD

**Issue by wangningbin** [ubicomplab/rPPG-Toolbox#97]
Hi,for the Physnet model, the input of the network mentioned by the author in the original text is the original video frame, but the frame difference normalization method is used in the yaml file of config. I don't know whether this will affect the test results

**Comment by xliucs** [comment]
Hi we have been testing multiple different input types and found out only normlaized frames can yield reasonable results. For raw frames / standardized frames, we all got MAE 10+. I actually just emailed the authors and hopefully willl hear back from them soon. BTW, the toolbox is down due to a recent merge last night. Our team is trying to fix it tonight.

**Comment by xliucs** [comment]
Feel free to open it if you have any more questions.
